apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-creds-control-config
data:
  read_enabled: "false"
  write_enabled: "false"
  xname_include: ".*"
  xname_exclude: ""
  username_include: "^Administrator|admin$"
  username_exclude: ""
  password_length: "15"
  password_characters: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

